# Generated by Django 5.1.6 on 2025-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('persons', models.IntegerField()),
                ('date', models.DateField(verbose_name='')),
            ],
        ),
    ]
